# AVSS09/tools/AVSS09Scorer

AVSS09Scorer=AVSS09Scorer.pl
AVSS09Scorer_tester_dir=../../test/AVSS09Scorer

all:
	@echo "Nothing to do"

install:
	@echo "Nothing to do for install"

check:	${AVSS09Scorer_tester_dir}/Makefile ${AVSS09Scorer}
	@(cd ${AVSS09Scorer_tester_dir}; make $@)
