# CLEAR07/tools/CLEARDTScorer

CLEARDTScorer=CLEARDTScorer.pl
CLEARDTScorer_tester_dir=../../test/CLEARDTScorer

all:
	@echo "Nothing to do"

install:
	@echo "Nothing to do for install"

check:	${CLEARDTScorer_tester_dir}/Makefile ${CLEARDTScorer}
	@(cd ${CLEARDTScorer_tester_dir}; make $@)
