# KWSEval

CPANP_IH=../common/tools/cpanp_installhelper/cpanp_installhelper.sh

all:
	@echo "Nothing to do"

install:
	@echo "Nothing to do for install"

check:
	@(cd test; make $@)

perl_install:
	@echo "-- Nothing extra for KWSEval"
