# CLEAR07/tools/CLEARTRScorer

CLEARTRScorer=CLEARTRScorer.pl
CLEARTRScorer_tester_dir=../../test/CLEARTRScorer

all:
	@echo "Nothing to do"

install:
	@echo "Nothing to do for install"

check:	${CLEARTRScorer_tester_dir}/Makefile ${CLEARTRScorer}
	@(cd ${CLEARTRScorer_tester_dir}; make $@)
