# DEVA/test

all:
	@echo "Nothing to do"

install:
	@echo "Nothing to do for install"

makecompcheckfiles makecheckfiles check:
	@(cd ../../common/test/SQLite_tools; make $@)
	@(cd DEVA_cli; make $@)
	@echo "***** All tests ran succesfully"
