# From within: tools/TV08Scorer

TV08Scorer=TV08Scorer.pl
TV08Scorer_tester_dir=../../test/TV08Scorer

all:
	@echo "Nothing to do"

install:
	@echo "Nothing to do for install"

check:	${TV08Scorer_tester_dir}/Makefile
	(cd ${TV08Scorer_tester_dir}; make check)
