# TrecVid08/tools/TV08MergeHelper

TV08MergeHelper=TV08MergeHelper.pl
TV08MergeHelper_tester_dir=../../test/TV08MergeHelper

all:
	@echo "Nothing to do"

install:
	@echo "Nothing to do for install"

check:	${TV08MergeHelper_tester_dir}/Makefile ${TV08MergeHelper}
	@(cd ${TV08MergeHelper_tester_dir}; make $@)
