
check:
	(cd Pre; make check)
	(cd TV08ViperValidator; make check)
	(cd TV08Scorer; make check)

makecheckfiles:
	(cd Pre; make check)
	(cd TV08ViperValidator; make makecheckfiles)
	(cd TV08Scorer; make makecheckfiles)
