# TrecVid08/tools/TV08ViperValidator

TV08ViperValidator=TV08ViperValidator.pl
TV08ViperValidator_tester_dir=../../test/TV08ViperValidator

all:
	@echo "Nothing to do"

install:
	@echo "Nothing to do for install"

check:	${TV08ViperValidator_tester_dir}/Makefile
	@(cd ${TV08ViperValidator_tester_dir}; make $@)
