# CLEAR07/tools/CLEARDTViperValidator

CLEARDTViperValidator=CLEARDTViperValidator.pl
CLEARDTViperValidator_tester_dir=../../test/CLEARDTViperValidator

all:
	@echo "Nothing to do"

install:
	@echo "Nothing to do for install"

check:	${CLEARDTViperValidator_tester_dir}/Makefile ${CLEARDTViperValidator}
	@(cd ${CLEARDTViperValidator_tester_dir}; make $@)
