# CLEAR07/tools/CLEARTRViperValidator

CLEARTRViperValidator=CLEARTRViperValidator.pl
CLEARTRViperValidator_tester_dir=../../test/CLEARTRViperValidator

all:
	@echo "Nothing to do"

install:
	@echo "Nothing to do for install"

check:	${CLEARTRViperValidator_tester_dir}/Makefile ${CLEARTRViperValidator}
	@(cd ${CLEARTRViperValidator_tester_dir}; make $@)
