# AVSS09/tools/AVSS09ViPERValidator

AVSS09ViPERValidator=AVSS09ViPERValidator.pl
AVSS09ViPERValidator_tester_dir=../../test/AVSS09ViPERValidator

all:
	@echo "Nothing to do"

install:
	@echo "Nothing to do for install"

check:	${AVSS09ViPERValidator_tester_dir}/Makefile ${AVSS09ViPERValidator}
	@(cd ${AVSS09ViPERValidator_tester_dir}; make $@)
